# Generated by Django 6.0 on 2026-01-04 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0002_alter_asset_symbol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='trade_type',
            field=models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], max_length=10),
        ),
    ]
